# -*- coding: utf-8 -*-
"""preprocessing_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TrwSL1p8vsI0OfeIgakoOdlgkZbxvJlq
"""

import pandas as pd

# Reading the CSV file
student_data = pd.read_csv("/content/StudentsPerformance.csv")

# Getting the info of the complete CSV
print(student_data.info())

# Understanding the data and dimensions
print(student_data.columns)
print(student_data.shape)

# Getting the top rows
print(student_data.head())

# Getting the bottom rows
print(student_data.tail())

# Getting the data structure
print(student_data.dtypes)

# Converting columns to categorical type
student_data['gender'] = student_data['gender'].astype('category')
student_data['race/ethnicity'] = student_data['race/ethnicity'].astype('category')
student_data['parental level of education'] = student_data['parental level of education'].astype('category')
student_data['test preparation course'] = student_data['test preparation course'].astype('category')

# Removing unnecessary columns
student_data.drop(columns=['lunch'], inplace=True)

# Summary statistics
print(student_data.describe())

# Checking for missing values
print(student_data.isna().any())

# Saving the clean data
student_data.to_csv("/content/clean_StudentsData.csv", index=False)